/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerCategory } from "./partnerCategory";

export interface CreatePartnerRegistrationDraftBusinessInfoRequest {
  /**
   * @minLength 2
   * @maxLength 255
   */
  businessName: string;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
  category: PartnerCategory;
  /**
   * @maxLength 1000
   * @nullable
   */
  logoUrl?: string | null;
}
