/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerRegistrationDraftBusinessInfo } from "./partnerRegistrationDraftBusinessInfo";
import type { PartnerRegistrationDraftContacts } from "./partnerRegistrationDraftContacts";
import type { PartnerRegistrationStep } from "./partnerRegistrationStep";

export interface GetPartnerRegistrationDraftResponse {
  draftId: string;
  status: string;
  completedSteps: PartnerRegistrationStep[];
  businessInfo?: PartnerRegistrationDraftBusinessInfo;
  contacts?: PartnerRegistrationDraftContacts;
}
