/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerCategory } from "./partnerCategory";

export interface PartnerRegistrationDraftBusinessInfo {
  businessName?: string;
  /** @nullable */
  description?: string | null;
  category?: PartnerCategory;
}
