/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export type PartnerCategory =
  (typeof PartnerCategory)[keyof typeof PartnerCategory];

export const PartnerCategory = {
  COFFEE_SHOP: "COFFEE_SHOP",
  RESTAURANT: "RESTAURANT",
  FITNESS: "FITNESS",
  BEAUTY: "BEAUTY",
  EDUCATION: "EDUCATION",
  HEALTH: "HEALTH",
  ENTERTAINMENT: "ENTERTAINMENT",
  OTHER: "OTHER",
} as const;
