/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerRegistrationDraftStatus } from "./partnerRegistrationDraftStatus";
import type { PartnerRegistrationStep } from "./partnerRegistrationStep";

export interface PartnerRegistrationDraftStepResponse {
  draftId: string;
  status: PartnerRegistrationDraftStatus;
  currentStep: PartnerRegistrationStep;
  completedSteps: PartnerRegistrationStep[];
}
