/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerBranch } from "./partnerBranch";
import type { PartnerOffer } from "./partnerOffer";

export interface PartnerResponse {
  id: string;
  name: string;
  branches: PartnerBranch[];
  offers: PartnerOffer[];
}
