/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerOfferListItemResponse } from "./partnerOfferListItemResponse";

export interface PartnerOffersResponse {
  offers: PartnerOfferListItemResponse[];
}
