/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export type PartnerRegistrationDraftStatus =
  (typeof PartnerRegistrationDraftStatus)[keyof typeof PartnerRegistrationDraftStatus];

export const PartnerRegistrationDraftStatus = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
} as const;
