/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export interface PartnerBranch {
  id: string;
  name: string;
  address: string;
}
