/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Текущий статус оффера
 */
export type PartnerOfferStatus =
  (typeof PartnerOfferStatus)[keyof typeof PartnerOfferStatus];

export const PartnerOfferStatus = {
  ACTIVE: "ACTIVE",
  DRAFT: "DRAFT",
  ARCHIVED: "ARCHIVED",
} as const;
