/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export type PartnerRegistrationStep =
  (typeof PartnerRegistrationStep)[keyof typeof PartnerRegistrationStep];

export const PartnerRegistrationStep = {
  BUSINESS_INFO: "BUSINESS_INFO",
  CONTACTS: "CONTACTS",
} as const;
