/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export interface PartnerStatistics {
  /**
   * Количество активных офферов
   * @minimum 0
   */
  activeOffers: number;
  /**
   * Общее количество офферов
   * @minimum 0
   */
  totalOffers: number;
  /**
   * Количество доступных для использования кодов
   * @minimum 0
   */
  availableCodes: number;
  /**
   * Общее количество выпущенных кодов
   * @minimum 0
   */
  totalCodes: number;
  /**
   * Количество использованных кодов за всё время
   * @minimum 0
   */
  usedCodes: number;
  /**
   * Количество точек партнёра
   * @minimum 0
   */
  locationsCount: number;
  /**
   * Количество городов присутствия партнёра
   * @minimum 0
   */
  citiesCount: number;
}
