/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import type { PartnerCategory } from "./partnerCategory";

export interface SavePartnerRegistrationDraftBusinessInfoRequest {
  /** @nullable */
  draftId?: string | null;
  /**
   * @minLength 2
   * @maxLength 100
   */
  businessName: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  description?: string | null;
  category: PartnerCategory;
}
