/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export interface SavePartnerRegistrationDraftContactInfoRequest {
  /** @nullable */
  draftId?: string | null;
  /**
   * @minLength 2
   * @maxLength 100
   */
  contactName: string;
  contactPhone: string;
  /**
   * @maxLength 255
   * @nullable
   */
  contactEmail?: string | null;
}
