/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */

export interface SubmitPartnerRegistrationDraftResponse {
  draftId: string;
  status: string;
  partnerId: string;
}
