/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { PartnerResponse } from "../../schemas";

export const getGetPartnerResponseMock = (): PartnerResponse => ({
  id: "3d0a4c2a-9d5c-4e4d-97cc-2c96a5f6b123",
  name: "Макаронная",
  statistics: {
    activeOffers: 8,
    totalOffers: 12,
    availableCodes: 1256,
    totalCodes: 2300,
    usedCodes: 1044,
    locationsCount: 5,
    citiesCount: 2,
  },
  branches: [
    {
      id: "7f4b6b3e-2d62-4d8e-b0d5-35f8c7c91a11",
      name: "Советская",
      address: "Советская, 345",
    },
    {
      id: "2d9c9134-f86d-46c4-b35c-a467638ab211",
      name: "Токтогула",
      address: "Токтогула, 125",
    },
  ],
  offers: [
    {
      id: "1b4f02e8-a111-4c2a-9d5c-4e4d97cc2c96",
      name: "Скидка 10%",
      activationDate: "2026-08-06",
    },
    {
      id: "6a84f2b1-3907-47e4-9022-49d319114e88",
      name: "Бесплатный напиток к заказу",
      activationDate: "2026-08-10",
    },
  ],
});

export const getGetPartnerMockHandler = (
  overrideResponse?:
    | PartnerResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PartnerResponse> | PartnerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/partners/:partnerId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPartnerResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnersMock = () => [getGetPartnerMockHandler()];
