/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { PartnerResponse } from "../../schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPartnerResponse200 = {
  data: PartnerResponse;
  status: 200;
};

export type getPartnerResponse404 = {
  data: void;
  status: 404;
};

export type getPartnerResponseSuccess = getPartnerResponse200 & {
  headers: Headers;
};
export type getPartnerResponseError = getPartnerResponse404 & {
  headers: Headers;
};

export type getPartnerResponse =
  getPartnerResponseSuccess | getPartnerResponseError;

export const getGetPartnerUrl = (partnerId: string) => {
  return `/api/partners/${partnerId}`;
};

/**
 * @summary Получить данные партнёра
 */
export const getPartner = async (
  partnerId: string,
  options?: RequestInit,
): Promise<getPartnerResponse> => {
  const res = await fetch(getGetPartnerUrl(partnerId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPartnerResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPartnerResponse;
};

export const getGetPartnerQueryKey = (partnerId: string) => {
  return [`/api/partners/${partnerId}`] as const;
};

export const getGetPartnerQueryOptions = <
  TData = Awaited<ReturnType<typeof getPartner>>,
  TError = void,
>(
  partnerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPartner>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPartnerQueryKey(partnerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPartner>>> = ({
    signal,
  }) => getPartner(partnerId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: partnerId !== null && partnerId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPartner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPartnerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPartner>>
>;
export type GetPartnerQueryError = void;

export function useGetPartner<
  TData = Awaited<ReturnType<typeof getPartner>>,
  TError = void,
>(
  partnerId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPartner>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartner>>,
          TError,
          Awaited<ReturnType<typeof getPartner>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPartner<
  TData = Awaited<ReturnType<typeof getPartner>>,
  TError = void,
>(
  partnerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPartner>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartner>>,
          TError,
          Awaited<ReturnType<typeof getPartner>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPartner<
  TData = Awaited<ReturnType<typeof getPartner>>,
  TError = void,
>(
  partnerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPartner>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить данные партнёра
 */

export function useGetPartner<
  TData = Awaited<ReturnType<typeof getPartner>>,
  TError = void,
>(
  partnerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPartner>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPartnerQueryOptions(partnerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
