/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { PartnerResponse } from "../../schemas";

export const getGetPartnerResponseMock = (
  overrideResponse: Partial<Extract<PartnerResponse, object>> = {},
): PartnerResponse => ({
  id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  branches: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    address: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  offers: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    activationDate: faker.date.past().toISOString().slice(0, 10),
  })),
  ...overrideResponse,
});

export const getGetPartnerMockHandler = (
  overrideResponse?:
    | PartnerResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PartnerResponse> | PartnerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/partners/:partnerId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPartnerResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnersMock = () => [getGetPartnerMockHandler()];
