/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { PartnerOffersResponse } from "../../schemas";

export const getGetPartnerOffersResponseMock = (): PartnerOffersResponse => ({
  offers: [
    {
      id: "c148461f-2364-47a4-9951-afc89efdf199",
      title: "Скидка 20% на кофе",
      status: "ACTIVE",
      validFrom: "2026-08-01",
      validTo: "2026-08-31",
      availableCodes: 74,
      totalCodes: 100,
    },
  ],
});

export const getGetPartnerOffersMockHandler = (
  overrideResponse?:
    | PartnerOffersResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PartnerOffersResponse> | PartnerOffersResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/partner/offers",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPartnerOffersResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnerOffersMock = () => [getGetPartnerOffersMockHandler()];
