/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { PartnerOffersResponse } from "../../schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPartnerOffersResponse200 = {
  data: PartnerOffersResponse;
  status: 200;
};

export type getPartnerOffersResponseSuccess = getPartnerOffersResponse200 & {
  headers: Headers;
};
export type getPartnerOffersResponse = getPartnerOffersResponseSuccess;

export const getGetPartnerOffersUrl = () => {
  return `/api/partner/offers`;
};

/**
 * Получить все офферы, принадлежащие текущему авторизованному партнёру
 * @summary Получить офферы текущего партнёра
 */
export const getPartnerOffers = async (
  options?: RequestInit,
): Promise<getPartnerOffersResponse> => {
  const res = await fetch(getGetPartnerOffersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPartnerOffersResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPartnerOffersResponse;
};

export const getGetPartnerOffersQueryKey = () => {
  return [`/api/partner/offers`] as const;
};

export const getGetPartnerOffersQueryOptions = <
  TData = Awaited<ReturnType<typeof getPartnerOffers>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPartnerOffers>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPartnerOffersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPartnerOffers>>
  > = ({ signal }) => getPartnerOffers({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPartnerOffers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPartnerOffersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPartnerOffers>>
>;
export type GetPartnerOffersQueryError = unknown;

export function useGetPartnerOffers<
  TData = Awaited<ReturnType<typeof getPartnerOffers>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPartnerOffers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartnerOffers>>,
          TError,
          Awaited<ReturnType<typeof getPartnerOffers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPartnerOffers<
  TData = Awaited<ReturnType<typeof getPartnerOffers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPartnerOffers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartnerOffers>>,
          TError,
          Awaited<ReturnType<typeof getPartnerOffers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPartnerOffers<
  TData = Awaited<ReturnType<typeof getPartnerOffers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPartnerOffers>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить офферы текущего партнёра
 */

export function useGetPartnerOffers<
  TData = Awaited<ReturnType<typeof getPartnerOffers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPartnerOffers>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPartnerOffersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
