/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { SubmitPartnerRegistrationDraftResponse } from "../../schemas";

export type submitPartnerRegistrationDraftResponse200 = {
  data: SubmitPartnerRegistrationDraftResponse;
  status: 200;
};

export type submitPartnerRegistrationDraftResponseSuccess =
  submitPartnerRegistrationDraftResponse200 & {
    headers: Headers;
  };
export type submitPartnerRegistrationDraftResponse =
  submitPartnerRegistrationDraftResponseSuccess;

export const getSubmitPartnerRegistrationDraftUrl = (draftId: string) => {
  return `/api/partner-registration/drafts/${draftId}/submit`;
};

/**
 * Завершает черновик регистрации партнёра. После успешного завершения статус черновика меняется с DRAFT на SUBMITTED. Для MVP система создаёт партнёра в статусе PENDING.
 * @summary Завершить регистрацию партнёра
 */
export const submitPartnerRegistrationDraft = async (
  draftId: string,
  options?: RequestInit,
): Promise<submitPartnerRegistrationDraftResponse> => {
  const res = await fetch(getSubmitPartnerRegistrationDraftUrl(draftId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitPartnerRegistrationDraftResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitPartnerRegistrationDraftResponse;
};

export const getSubmitPartnerRegistrationDraftMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>,
    TError,
    { draftId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>,
  TError,
  { draftId: string },
  TContext
> => {
  const mutationKey = ["submitPartnerRegistrationDraft"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>,
    { draftId: string }
  > = (props) => {
    const { draftId } = props ?? {};

    return submitPartnerRegistrationDraft(draftId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitPartnerRegistrationDraftMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>
>;

export type SubmitPartnerRegistrationDraftMutationError = unknown;

/**
 * @summary Завершить регистрацию партнёра
 */
export const useSubmitPartnerRegistrationDraft = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>,
      TError,
      { draftId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitPartnerRegistrationDraft>>,
  TError,
  { draftId: string },
  TContext
> => {
  return useMutation(
    getSubmitPartnerRegistrationDraftMutationOptions(options),
    queryClient,
  );
};
