/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { SubmitPartnerRegistrationDraftResponse } from "../../schemas";

export const getSubmitPartnerRegistrationDraftResponseMock =
  (): SubmitPartnerRegistrationDraftResponse => ({
    draftId: "b7b7c3c1-2b15-4f7c-8c3d-1b4f02e8a111",
    status: "SUBMITTED",
    partnerId: "3d0a4c2a-9d5c-4e4d-97cc-2c96a5f6b123",
  });

export const getSubmitPartnerRegistrationDraftMockHandler = (
  overrideResponse?:
    | SubmitPartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SubmitPartnerRegistrationDraftResponse>
        | SubmitPartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/partner-registration/drafts/:draftId/submit",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSubmitPartnerRegistrationDraftResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnerRegistrationDraftsMock = () => [
  getSubmitPartnerRegistrationDraftMockHandler(),
];
