/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreatePartnerRegistrationDraftBusinessInfoRequest,
  PartnerRegistrationDraftStepResponse,
} from "../../schemas";

export type createPartnerRegistrationDraftWithBusinessInfoResponse201 = {
  data: PartnerRegistrationDraftStepResponse;
  status: 201;
};

export type createPartnerRegistrationDraftWithBusinessInfoResponseSuccess =
  createPartnerRegistrationDraftWithBusinessInfoResponse201 & {
    headers: Headers;
  };
export type createPartnerRegistrationDraftWithBusinessInfoResponse =
  createPartnerRegistrationDraftWithBusinessInfoResponseSuccess;

export const getCreatePartnerRegistrationDraftWithBusinessInfoUrl = () => {
  return `/api/partner-registration-drafts/business-info`;
};

/**
 * @summary Create partner registration draft with business info
 */
export const createPartnerRegistrationDraftWithBusinessInfo = async (
  createPartnerRegistrationDraftBusinessInfoRequest: CreatePartnerRegistrationDraftBusinessInfoRequest,
  options?: RequestInit,
): Promise<createPartnerRegistrationDraftWithBusinessInfoResponse> => {
  const res = await fetch(
    getCreatePartnerRegistrationDraftWithBusinessInfoUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createPartnerRegistrationDraftBusinessInfoRequest),
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPartnerRegistrationDraftWithBusinessInfoResponse["data"] =
    body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createPartnerRegistrationDraftWithBusinessInfoResponse;
};

export const getCreatePartnerRegistrationDraftWithBusinessInfoMutationOptions =
  <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>
      >,
      TError,
      { data: CreatePartnerRegistrationDraftBusinessInfoRequest },
      TContext
    >;
    fetch?: RequestInit;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>>,
    TError,
    { data: CreatePartnerRegistrationDraftBusinessInfoRequest },
    TContext
  > => {
    const mutationKey = ["createPartnerRegistrationDraftWithBusinessInfo"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>
      >,
      { data: CreatePartnerRegistrationDraftBusinessInfoRequest }
    > = (props) => {
      const { data } = props ?? {};

      return createPartnerRegistrationDraftWithBusinessInfo(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
  };

export type CreatePartnerRegistrationDraftWithBusinessInfoMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>>
  >;
export type CreatePartnerRegistrationDraftWithBusinessInfoMutationBody =
  CreatePartnerRegistrationDraftBusinessInfoRequest;
export type CreatePartnerRegistrationDraftWithBusinessInfoMutationError =
  unknown;

/**
 * @summary Create partner registration draft with business info
 */
export const useCreatePartnerRegistrationDraftWithBusinessInfo = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>
      >,
      TError,
      { data: CreatePartnerRegistrationDraftBusinessInfoRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPartnerRegistrationDraftWithBusinessInfo>>,
  TError,
  { data: CreatePartnerRegistrationDraftBusinessInfoRequest },
  TContext
> => {
  return useMutation(
    getCreatePartnerRegistrationDraftWithBusinessInfoMutationOptions(options),
    queryClient,
  );
};
