/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  GetPartnerRegistrationDraftResponse,
  PartnerRegistrationDraftResponse,
} from "../../schemas";

export const getSavePartnerRegistrationDraftBusinessInfoResponseMock =
  (): PartnerRegistrationDraftResponse => ({
    draftId: "b7b7c3c1-2b15-4f7c-8c3d-1b4f02e8a111",
  });

export const getSavePartnerRegistrationDraftContactInfoResponseMock =
  (): PartnerRegistrationDraftResponse => ({
    draftId: "b7b7c3c1-2b15-4f7c-8c3d-1b4f02e8a111",
  });

export const getGetPartnerRegistrationDraftResponseMock =
  (): GetPartnerRegistrationDraftResponse => ({
    draftId: "7f4b6b3e-2d62-4d8e-b0d5-35f8c7c91a11",
    status: "DRAFT",
    completedSteps: ["BUSINESS_INFO", "CONTACTS"],
    businessInfo: {
      businessName: "Sierra Coffee",
      description: "Кофейня в центре Бишкека",
      category: "COFFEE_SHOP",
    },
    contacts: {
      contactName: "Азамат",
      contactPhone: "+996700123456",
      contactEmail: "partner@example.kg",
    },
  });

export const getSavePartnerRegistrationDraftBusinessInfoMockHandler = (
  overrideResponse?:
    | PartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) =>
        | Promise<PartnerRegistrationDraftResponse>
        | PartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/partner-registration/draft/business-info",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSavePartnerRegistrationDraftBusinessInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getSavePartnerRegistrationDraftContactInfoMockHandler = (
  overrideResponse?:
    | PartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) =>
        | Promise<PartnerRegistrationDraftResponse>
        | PartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/partner-registration/draft/contact-info",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSavePartnerRegistrationDraftContactInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPartnerRegistrationDraftMockHandler = (
  overrideResponse?:
    | GetPartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetPartnerRegistrationDraftResponse>
        | GetPartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/partner-registration/drafts/:draftId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPartnerRegistrationDraftResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnerRegistrationMock = () => [
  getSavePartnerRegistrationDraftBusinessInfoMockHandler(),
  getSavePartnerRegistrationDraftContactInfoMockHandler(),
  getGetPartnerRegistrationDraftMockHandler(),
];
