/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Employee Benefits API
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import { PartnerCategory, PartnerRegistrationStep } from "../../schemas";
import type {
  GetPartnerRegistrationDraftResponse,
  PartnerRegistrationDraftResponse,
} from "../../schemas";

export const getSavePartnerRegistrationDraftBusinessInfoResponseMock = (
  overrideResponse: Partial<
    Extract<PartnerRegistrationDraftResponse, object>
  > = {},
): PartnerRegistrationDraftResponse => ({
  draftId: faker.string.uuid(),
  ...overrideResponse,
});

export const getSavePartnerRegistrationDraftContactInfoResponseMock = (
  overrideResponse: Partial<
    Extract<PartnerRegistrationDraftResponse, object>
  > = {},
): PartnerRegistrationDraftResponse => ({
  draftId: faker.string.uuid(),
  ...overrideResponse,
});

export const getGetPartnerRegistrationDraftResponseMock = (
  overrideResponse: Partial<
    Extract<GetPartnerRegistrationDraftResponse, object>
  > = {},
): GetPartnerRegistrationDraftResponse => ({
  draftId: faker.string.uuid(),
  status: faker.string.alpha({ length: { min: 10, max: 20 } }),
  completedSteps: faker.helpers.arrayElements(
    Object.values(PartnerRegistrationStep),
  ),
  businessInfo: faker.helpers.arrayElement([
    {
      businessName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      description: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        undefined,
      ]),
      category: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(PartnerCategory)),
        undefined,
      ]),
    },
    undefined,
  ]),
  contacts: faker.helpers.arrayElement([
    {
      contactName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      contactPhone: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      contactEmail: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.internet.email(), null]),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSavePartnerRegistrationDraftBusinessInfoMockHandler = (
  overrideResponse?:
    | PartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) =>
        | Promise<PartnerRegistrationDraftResponse>
        | PartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/partner-registration/draft/business-info",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSavePartnerRegistrationDraftBusinessInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getSavePartnerRegistrationDraftContactInfoMockHandler = (
  overrideResponse?:
    | PartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) =>
        | Promise<PartnerRegistrationDraftResponse>
        | PartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/partner-registration/draft/contact-info",
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSavePartnerRegistrationDraftContactInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPartnerRegistrationDraftMockHandler = (
  overrideResponse?:
    | GetPartnerRegistrationDraftResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetPartnerRegistrationDraftResponse>
        | GetPartnerRegistrationDraftResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/partner-registration/drafts/:draftId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPartnerRegistrationDraftResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPartnerRegistrationMock = () => [
  getSavePartnerRegistrationDraftBusinessInfoMockHandler(),
  getSavePartnerRegistrationDraftContactInfoMockHandler(),
  getGetPartnerRegistrationDraftMockHandler(),
];
